// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/image_serviice.proto

#include "protos/image_serviice.pb.h"
#include "protos/image_serviice.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace image_service {

static const char* ImageService_method_names[] = {
  "/image_service.ImageService/GetImage",
};

std::unique_ptr< ImageService::Stub> ImageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageService::Stub> stub(new ImageService::Stub(channel, options));
  return stub;
}

ImageService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetImage_(ImageService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ImageService::Stub::GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::image_service::ImageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::image_service::ImageRequest, ::image_service::ImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetImage_, context, request, response);
}

void ImageService::Stub::async::GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::image_service::ImageRequest, ::image_service::ImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, std::move(f));
}

void ImageService::Stub::async::GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>* ImageService::Stub::PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::image_service::ImageResponse, ::image_service::ImageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetImage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>* ImageService::Stub::AsyncGetImageRaw(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetImageRaw(context, request, cq);
  result->StartCall();
  return result;
}

ImageService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageService::Service, ::image_service::ImageRequest, ::image_service::ImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ImageService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::image_service::ImageRequest* req,
             ::image_service::ImageResponse* resp) {
               return service->GetImage(ctx, req, resp);
             }, this)));
}

ImageService::Service::~Service() {
}

::grpc::Status ImageService::Service::GetImage(::grpc::ServerContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace image_service

