// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/image_service.proto
#ifndef GRPC_protos_2fimage_5fservice_2eproto__INCLUDED
#define GRPC_protos_2fimage_5fservice_2eproto__INCLUDED

#include "protos/image_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace image_service {

class ImageService final {
 public:
  static constexpr char const* service_full_name() {
    return "image_service.ImageService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::image_service::ImageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::ImageResponse>> AsyncGetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::ImageResponse>>(AsyncGetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::ImageResponse>> PrepareAsyncGetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::ImageResponse>>(PrepareAsyncGetImageRaw(context, request, cq));
    }
    virtual ::grpc::Status SetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::image_service::SetImageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::SetImageResponse>> AsyncSetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::SetImageResponse>>(AsyncSetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::SetImageResponse>> PrepareAsyncSetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image_service::SetImageResponse>>(PrepareAsyncSetImageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest* request, ::image_service::SetImageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest* request, ::image_service::SetImageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image_service::ImageResponse>* AsyncGetImageRaw(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image_service::ImageResponse>* PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image_service::SetImageResponse>* AsyncSetImageRaw(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image_service::SetImageResponse>* PrepareAsyncSetImageRaw(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::image_service::ImageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>> AsyncGetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>>(AsyncGetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>> PrepareAsyncGetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>>(PrepareAsyncGetImageRaw(context, request, cq));
    }
    ::grpc::Status SetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::image_service::SetImageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::SetImageResponse>> AsyncSetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::SetImageResponse>>(AsyncSetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::SetImageResponse>> PrepareAsyncSetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image_service::SetImageResponse>>(PrepareAsyncSetImageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response, std::function<void(::grpc::Status)>) override;
      void GetImage(::grpc::ClientContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest* request, ::image_service::SetImageResponse* response, std::function<void(::grpc::Status)>) override;
      void SetImage(::grpc::ClientContext* context, const ::image_service::SetImageRequest* request, ::image_service::SetImageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>* AsyncGetImageRaw(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::image_service::ImageResponse>* PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::image_service::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::image_service::SetImageResponse>* AsyncSetImageRaw(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::image_service::SetImageResponse>* PrepareAsyncSetImageRaw(::grpc::ClientContext* context, const ::image_service::SetImageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetImage_;
    const ::grpc::internal::RpcMethod rpcmethod_SetImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetImage(::grpc::ServerContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response);
    virtual ::grpc::Status SetImage(::grpc::ServerContext* context, const ::image_service::SetImageRequest* request, ::image_service::SetImageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetImage(::grpc::ServerContext* context, ::image_service::ImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::image_service::ImageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetImage() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetImage(::grpc::ServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetImage(::grpc::ServerContext* context, ::image_service::SetImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::image_service::SetImageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetImage<WithAsyncMethod_SetImage<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::image_service::ImageRequest, ::image_service::ImageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::image_service::ImageRequest* request, ::image_service::ImageResponse* response) { return this->GetImage(context, request, response); }));}
    void SetMessageAllocatorFor_GetImage(
        ::grpc::MessageAllocator< ::image_service::ImageRequest, ::image_service::ImageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::image_service::ImageRequest, ::image_service::ImageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetImage(
      ::grpc::CallbackServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetImage() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::image_service::SetImageRequest, ::image_service::SetImageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::image_service::SetImageRequest* request, ::image_service::SetImageResponse* response) { return this->SetImage(context, request, response); }));}
    void SetMessageAllocatorFor_SetImage(
        ::grpc::MessageAllocator< ::image_service::SetImageRequest, ::image_service::SetImageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::image_service::SetImageRequest, ::image_service::SetImageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetImage(::grpc::ServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetImage(
      ::grpc::CallbackServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetImage<WithCallbackMethod_SetImage<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetImage() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetImage(::grpc::ServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetImage() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetImage(::grpc::ServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetImage(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetImage() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetImage(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetImage(::grpc::ServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetImage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::image_service::ImageRequest, ::image_service::ImageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::image_service::ImageRequest, ::image_service::ImageResponse>* streamer) {
                       return this->StreamedGetImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::image_service::ImageRequest* /*request*/, ::image_service::ImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::image_service::ImageRequest,::image_service::ImageResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetImage() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::image_service::SetImageRequest, ::image_service::SetImageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::image_service::SetImageRequest, ::image_service::SetImageResponse>* streamer) {
                       return this->StreamedSetImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetImage(::grpc::ServerContext* /*context*/, const ::image_service::SetImageRequest* /*request*/, ::image_service::SetImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::image_service::SetImageRequest,::image_service::SetImageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetImage<WithStreamedUnaryMethod_SetImage<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetImage<WithStreamedUnaryMethod_SetImage<Service > > StreamedService;
};

}  // namespace image_service


#endif  // GRPC_protos_2fimage_5fservice_2eproto__INCLUDED
