CREATE TABLE UserChats
(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserID1 INT,
    UserID2 INT,
    CreateTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID1) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY (UserID2) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE INDEX UserChats_idx_UserID1 on UserChats (UserID1);
CREATE INDEX UserChats_idx_UserID2 on UserChats (UserID2);